/*
 * Concatenate ./styles/*.css into the single styles.css Obsidian loads.
 *
 * Obsidian only reads one stylesheet per plugin, but a 1900-line file is not
 * something anyone wants to edit. The shards are listed in the order they must
 * appear: the cascade depends on it, so the order is explicit here rather than
 * alphabetical and there is no "just add a file" shortcut.
 */

import fs from "fs";
import path from "path";

const STYLE_DIR = "styles";
const OUTFILE = "styles.css";

/** Concatenation order. Changing it changes which rule wins. */
export const SHARDS = [
  "shell-and-tree.css",
  "pane-and-grid.css",
  "cards.css",
  "detail-modal.css",
  "folder-stack.css",
  "lightbox.css",
  "confirm.css",
  "heatmap-grid.css",
  "heatmap-legend.css",
  "settings-pane.css",
  "export.css",
];

const BANNER = `/*
Generated by build-styles.mjs — do not edit.
Edit the shards in ./styles/ instead; this file is overwritten on every build.
*/

`;

/**
 * Join every shard, in order, into the stylesheet Obsidian loads.
 *
 * Line endings are normalised to LF: the shards arrived as CRLF from the
 * pre-split file, and a join that left one shard's CRLF next to another's LF
 * produced a stylesheet with two endings in it, which every diff tool then
 * reports as a whole-file rewrite.
 */
export function readStyles() {
  const parts = SHARDS.map((name) => {
    const file = path.join(STYLE_DIR, name);
    if (!fs.existsSync(file)) throw new Error(`missing style shard: ${file}`);
    return fs.readFileSync(file, "utf8").replace(/\r\n/g, "\n").replace(/\s+$/, "");
  });
  return BANNER + parts.join("\n\n") + "\n";
}

export function buildStyles() {
  const css = readStyles();
  const previous = fs.existsSync(OUTFILE) ? fs.readFileSync(OUTFILE, "utf8") : null;
  if (previous === css) return false;
  fs.writeFileSync(OUTFILE, css);
  return true;
}

/** In dev mode, rebuild whenever a shard changes. */
export function watchStyles(onRebuild) {
  for (const name of SHARDS) {
    fs.watch(path.join(STYLE_DIR, name), () => {
      if (buildStyles()) onRebuild?.(name);
    });
  }
}
